//
//  DataEntry.swift
//  Registration App
//
//  Created by Yousef Arafa on 2/13/20.
//  Copyright © 2020 Yousef Arafa. All rights reserved.
//

import Foundation

extension MovieViewController {

    func setData(){
        movies += [Movie(image: "uncut-gems", title: "Uncut Gems", desc: "Adam Sandler is such a recognizable face in Hollywood that simply presenting a battered and bruised version of him surrounded by ominous darkness is enough to make the “Uncut Gems” poster a knockout.",imdbLink: "https://www.imdb.com/title/tt5727208/?ref_=nv_sr_srsg_0", trailer: "https://www.youtube.com/watch?v=vTfJp2Ts9X8"),
                   Movie(image: "ad-astra", title: "Ad Astra", desc: "James Gray’s science-fiction stunner “Ad Astra” issued one poster with Brad Pitt’s big, beautiful face front and center, but it turns out this poster that hid its leading man was far more effective in selling the mind-bending drama of the film’s plot.",imdbLink: "https://www.imdb.com/title/tt2935510/?ref_=fn_al_tt_1", trailer: "https://www.youtube.com/watch?v=SYLQdxec5lM"),
                   Movie(image: "glass", title: "Glass", desc: "“Glass” was supposed to be a celebratory career peak for M. Night Shyamalan as the sequel to “Unbreakable” and “Split,” but instead it ended up being the biggest disappointment of the director’s career. Final product aside, the film’s illustrated one-sheet remains one of the year’s best, perfectly capturing the comic-book heart of Shyamalan’s vision.",imdbLink: "https://www.imdb.com/title/tt6823368/?ref_=fn_al_tt_1", trailer: "https://www.youtube.com/watch?v=95ghQs5AmNk"),
                   Movie(image: "john-wick", title: "John Wick: Chapter 3 – Parabellum", desc: "Three movies in and Lionsgate knows how to sell the “John Wick” franchise to fans with an action-packed punch. If this ingenious one-sheet for “John Wick: Chapter 3 – Parabellum” doesn’t get your blood pumping then nothing will.",imdbLink: "https://www.imdb.com/title/tt6146586/?ref_=fn_al_tt_1", trailer: "https://www.youtube.com/watch?v=pU8-7BX9uxs"),
                   Movie(image: "Joker", title: "Joker", desc: "The more attention-grabbing “Joker” posters couldn’t compete with the effect of the movie’s one-sheet teaser. By showing just a sneak peek of Joaquin Phoenix’s full Joker face makeup, the poster effortlessly draws the viewer’s curiosity.",imdbLink: "https://www.imdb.com/title/tt7286456/?ref_=fn_al_tt_1", trailer: "https://www.youtube.com/watch?v=zAGVQLHvwOY"),
                   Movie(image: "lucy-in-the-sky", title: "Lucy in the Sky", desc: "Noah Hawley’s feature directorial debut “Lucy in the Sky” received some of the worst reviews of 2019, and its horrendous box office was nothing to brag about either. If only the movie lived up to its impressive first trailer and poster.",imdbLink: "https://www.imdb.com/title/tt4682804/?ref_=nv_sr_srsg_0", trailer: "https://www.youtube.com/watch?v=vQP-L2pJzmk"),
                   Movie(image: "midsommar", title: "Midsommar", desc: "Bow down to Florence Pugh, the scream queen of 2019. The actress’ terrified close-up is a warning that Ari Aster’s “Midsommar” is bound to screw with your head and shatter your emotions to pieces.",imdbLink: "https://www.imdb.com/title/tt8772262/?ref_=nv_sr_srsg_0", trailer: "https://www.youtube.com/watch?v=1Vnghdsjmd0"),
                   Movie(image: "nightingale", title: "The Nightingale", desc: "Aisling Franciosi’s performance in Jennifer Kent’s bruising revenge drama “The Nightingale” is one of the year’s most gut-punching, and it’s no small feat that IFC Films was able to capture Franciosi’s wounded anger in one still image.",imdbLink: "https://www.imdb.com/title/tt4068576/?ref_=nv_sr_srsg_0", trailer: "https://www.youtube.com/watch?v=YuP8g_GQIgI"),
                   Movie(image: "souvenir", title: "The Souvenir", desc: "A24’s poster for “The Souvenir” takes the notion of writer-director Joanna Hogg reflecting on her coming-of-age experience quite literally. Capturing the reflections of stars Honor Swinton Byrne and Tom Burke, the poster speaks volumes to the relationship that plays out at the heart of the story.",imdbLink: "https://www.imdb.com/title/tt6920356/?ref_=fn_al_tt_1", trailer: "https://www.youtube.com/watch?v=t9Al2nC0vzY"),
                   Movie(image: "transit", title: "Transit", desc: "The poster for Christian Petzold’s remarkable “Transit” tells you everything you need to know about how a mysterious woman (Paula Beer) will bury herself into the soul of the film’s main character (Franz Rogowski).",imdbLink: "https://www.imdb.com/title/tt6675244/?ref_=nv_sr_srsg_0", trailer: "https://www.youtube.com/watch?v=R15ekRCq-eY"),
                   Movie(image: "us", title: "Us", desc: "Jordan Peele’s “Us” had one of the best posters of 2018 thanks to its inkblot teaser, and the film’s marketing strengths continued into this year with a striking official one-sheet featuring Lupita Nyong’o. The “Us” poster communicates the film’s plot more intriguingly than any trailer could.",imdbLink: "https://www.imdb.com/title/tt6857112/?ref_=nv_sr_srsg_3", trailer: "https://www.youtube.com/watch?v=1tzFRIQfwXg"),
                   Movie(image: "wendy", title: "Wendy", desc: "Benh Zeitlin will finally return next year with “Wendy,” which is debuting eight years after “Beasts of the Southern Wild.” The movie is debuting at the 2020 Sundance Film Festival. Fox Searchlight’s teaser poster for “Wendy” feels like a burnt photograph that has captured the forward momentum of youth in one still image.",imdbLink: "https://www.imdb.com/title/tt2420124/?ref_=nv_sr_srsg_0", trailer: "https://www.youtube.com/watch?v=KKktQFFcXL0")]
    }
}
